#!/usr/bin/env node
'use strict';

const { main } = require('./scripts/egomorph');

main(process.argv.slice(2)).then(code => {
  if (code) process.exit(code);
}).catch(err => {
  console.error(err && err.message ? err.message : String(err));
  process.exit(1);
});
