(function () {
  window.EgoMorphLocales = window.EgoMorphLocales || {};
  var base = window.EgoMorphLocales.de ? window.EgoMorphLocales.de.ui : {};
  window.EgoMorphLocales.en = { ui: Object.assign({}, base, {
    placeholder: 'Give Egomorph Core a task or question...', welcomeText: 'Welcome to Egomorph Core, your agentic AI workspace.',
    writerTitle: 'Egomorph Core Writer', writerLockNotice: 'The Writer agent requires an active generative backend.', writerSystemPrompt: 'You are Egomorph Core Writer, a precise English writing agent. Reply only with the requested text, without preface.',
    sendButton: 'Send', stopButton: 'Stop response', replyErrorPrefix: 'Error: {message}', emptyModelReply: 'The model returned an empty response.',
    agentThoughtLabel: '1. Reasoning summary', agentThoughtFallback: 'The request was reviewed and an appropriate response was prepared.', agentSkillLabel: '2. Skill access', agentFinalLabel: '--- Final answer ---',
    agentAnalyzingStatus: 'Analyzing the request…', agentModelWorkingStatus: 'The model is composing the answer…', agentFinalWaiting: 'Preparing the answer…', agentSkillRunning: 'Access in progress…', agentSkillCompleted: 'Access completed', agentSkillCompletedSources: '{count} sources used', agentSkillCompletedNoSources: 'Access completed, no sources found', agentSkillFailed: 'Access failed technically', agentSkillBlocked: 'Not started – skill, profile, or network permission is disabled', agentProcessingFailed: 'Processing could not be completed.',
    modelRequiredError: 'Enable a local LLM or select and configure the API/Codex profile.', settingsBtn: '⚙️ Settings', infoBtn: 'ℹ️ Info', clearChatBtn: 'Clear conversation',
    conversationsTitle: 'Conversations', newConversationBtn: '＋ New conversation', conversationUntitled: 'New conversation', conversationMessageCount: '{count} messages', conversationDelete: 'Delete conversation',
    conversationSidebarHint: 'Each conversation is stored locally and continues as its own App Server thread in Codex mode.', activeConversationLabel: 'Active conversation', youPrefix: 'You:',
    settingsTitle: 'Settings', settingsIntro: 'Configure Egomorph Core’s generative backends and agentic capabilities.', quickActionsTitle: 'Quick actions', quickActionsHint: 'Control history, voice, and stored data.',
    voiceActivate: 'Enable voice', voiceDeactivate: 'Disable voice', personalSectionTitle: 'Personal address', userNameLabel: 'Your name', saveUserNameBtn: 'Save', clearUserNameBtn: 'Delete',
    personalSectionHint: 'Egomorph Core can use this name as a local preference.', languageSectionTitle: 'Language', languageLabel: 'Language',
    infoText: 'Egomorph Core is a local, PWA-ready, agentic browser app with a local LLM and optional API or Codex backend.<br><br>Copyright CreateWithCode 2025 - 2026<br>MIT licensed.',
    resourceProfileTitle: 'Generative backend', resourceProfileIntro: 'Choose a generative backend for Egomorph Core.',
    resourceProfileFullName: 'Local', resourceProfileFullText: '- Generative browser LLM', resourceProfileFullMeta: 'Model-dependent memory usage, fully local', resourceProfileApiText: '- External API (OpenRouter / OpenAI / Ollama / LM Studio)',
    resourceProfileApiMeta: '~0 MB locally, requires an API endpoint', resourceProfileCodexText: '- Local Codex App Server with ChatGPT sign-in', resourceProfileCodexMeta: '~0 MB in the browser, requires the localhost Egomorph Core gateway',
    resourceProfileReloadHint: 'Profile changes take effect after reloading the page.', skillSettingsTitle: 'Skills', skillSettingsIntro: 'Manage installed skills, their permissions, profiles, and setup.',
    skillLoading: 'Loading skill manifests…', skillSystemUnavailable: 'The skill system is unavailable.', skillInstall: 'Install', skillUninstall: 'Uninstall', skillEnable: 'Enable skill', skillEnabled: 'Enabled', skillDisabled: 'Disabled', skillNotInstalled: 'Not installed',
    skillVersion: 'Version', skillLastRun: 'Last run', skillNeverRun: 'Never', skillPermissions: 'Required permissions', skillProfiles: 'Allowed profiles', skillSetup: 'Setup', skillSave: 'Save', skillSavedStatus: 'Saved', skillUnavailableForProfile: 'The skill or its required permissions are not enabled for the active profile.',
    skillProfileFull: 'Local', skillProfileApi: 'API', skillProfileCodex: 'Codex', skillPermissionNetwork: 'Internet access', skillPermissionNetworkDescription: 'May send search queries to external search services.', skillPermissionCredentials: 'Use local credentials', skillPermissionCredentialsDescription: 'May use locally stored Google credentials for searches.',
    internetSkillName: 'Internet research', internetSkillDescription: 'Loads current web sources as context for API and Codex responses.', internetProviderAuto: 'Automatic: Google, then fallbacks', internetProviderGoogle: 'Google Programmable Search', internetProviderFallback: 'DuckDuckGo/Wikipedia only',
    internetSkillEnabledLabel: 'Enable internet research', internetSkillWarning: 'Research requests are sent to the selected search provider.', internetSkillProviderLabel: 'Search provider', internetSkillGoogleHint: 'Fallback providers are used without Google configuration. Keys remain in the browser.',
    internetSkillSaveBtn: 'Save', internetSkillTestBtn: 'Test search', internetSkillSavedStatus: 'Saved', internetSkillTestingStatus: 'Testing...', internetSkillTestOkStatus: 'Search OK ({count} results)', internetSkillErrorStatusPrefix: 'Error: ', internetSkillTestQuery: 'Egomorph Core internet search',
    apiSettingsTitle: 'API settings', apiSettingsIntro: 'Connect Egomorph Core to an external OpenAI-compatible LLM.', apiSettingsWarning: 'API keys are stored in the browser. A proxy is safer for public deployments.',
    apiMaxTokensLabel: 'Max response tokens', apiMaxTokensHint: 'Applies only to API responses.', apiSaveBtn: 'Save', apiTestBtn: 'Test connection', apiExamplesTitle: 'Example configurations:', apiSavedStatus: 'Saved', apiTestingStatus: 'Testing...', apiConnectionOkStatus: 'Connection OK', apiErrorStatusPrefix: 'Error: ',
    codexSettingsTitle: 'Codex gateway', codexSettingsIntro: 'Uses the local Egomorph Core gateway to the official Codex CLI with a persistent App Server and streaming.', codexSettingsWarning: 'For trusted local use only. Do not copy cookies, access tokens, or auth.json into the app.',
    codexSetupTitle: 'Setup in 3 steps', codexStepLogin: 'Sign in once: <code>./egomorph codex login</code> or <code>./egomorph codex login --device-auth</code>.', codexStepBridge: 'Start the gateway: <code>./egomorph dashboard</code> or <code>./egomorph gateway</code>.',
    codexStepCheck: 'Save here and verify with <strong>Check status</strong>.', codexPersistentHint: 'After sign-in, Codex remains signed in locally; Egomorph Core stores only gateway URL, model, and token limit.', codexBridgeUrlLabel: 'Gateway URL',
    codexMaxTokensLabel: 'Max response tokens', codexMaxTokensHint: 'Applies only to Codex mode.', codexSaveBtn: 'Save', codexTestBtn: 'Test gateway', codexStatusBtn: 'Check status', codexSavedStatus: 'Saved', codexTestingStatus: 'Testing...', codexStatusChecking: 'Checking status...', codexConnectionOkStatus: 'Gateway OK', codexErrorStatusPrefix: 'Error: ',
    chatModelSettingsTitle: 'Local chat model (LLM)', reloadChatModelBtn: 'Load model', chatModelStatusIdle: 'No model loaded', chatModelLoading: 'Loading model...', chatModelNoTransformers: 'Transformers.js unavailable', chatModelErrorPrefix: 'Error: ', chatModelWaitingTransformers: 'Waiting for Transformers.js...', chatModelLoadingPct: 'Loading... {pct}%', chatModelInitializing: 'Initializing...', chatModelReady: 'Ready ({id})', chatModelNeedsLoad: 'Load a model first',
    chatModelApiActive: 'API mode active', chatModelCodexActive: 'Codex mode active', chatModelProfilePrefix: 'Profile: ', chatModelNoLocalLLM: 'no local LLM', llmMaxTokensLabel: 'Max tokens', llmEnabledLabel: 'Enable LLM responses', chatModelSettingsHint: '<code>text-generation</code> model for autonomous local responses. There is no rule-based fallback.', lightChatModelsTitle: 'Lightweight models:'
  }) };
})();
