(function () {
  window.EgoMorphLocales = window.EgoMorphLocales || {};
  var base = window.EgoMorphLocales.de ? window.EgoMorphLocales.de.ui : {};
  window.EgoMorphLocales.fr = { ui: Object.assign({}, base, {
    placeholder: 'Confie une tâche ou une question à Egomorph Core...', welcomeText: 'Bienvenue dans Egomorph Core, ton espace de travail IA agentique.',
    writerTitle: 'Egomorph Core Writer', writerLockNotice: 'L’agent Writer nécessite un backend génératif actif.', writerSystemPrompt: 'Tu es Egomorph Core Writer, un agent de rédaction français précis. Réponds uniquement avec le texte demandé, sans introduction.',
    sendButton: 'Envoyer', stopButton: 'Arrêter la réponse', replyErrorPrefix: 'Erreur : {message}', emptyModelReply: 'Le modèle a renvoyé une réponse vide.',
    agentThoughtLabel: '1. Résumé du raisonnement', agentThoughtFallback: 'La demande a été examinée et une réponse appropriée a été préparée.', agentSkillLabel: '2. Accès à la compétence', agentFinalLabel: '--- Réponse finale ---',
    agentAnalyzingStatus: 'Analyse de la demande…', agentModelWorkingStatus: 'Le modèle rédige la réponse…', agentFinalWaiting: 'Préparation de la réponse…', agentSkillRunning: 'Accès en cours…', agentSkillCompleted: 'Accès terminé', agentSkillCompletedSources: '{count} sources utilisées', agentSkillCompletedNoSources: 'Accès terminé, aucune source trouvée', agentSkillFailed: 'Échec technique de l’accès', agentSkillBlocked: 'Non démarré – compétence, profil ou autorisation réseau désactivé', agentProcessingFailed: 'Le traitement n’a pas pu être terminé.',
    modelRequiredError: 'Active un LLM local ou sélectionne et configure le profil API/Codex.', settingsBtn: '⚙️ Paramètres', infoBtn: 'ℹ️ Info', clearChatBtn: 'Effacer la conversation',
    conversationsTitle: 'Conversations', newConversationBtn: '＋ Nouvelle conversation', conversationUntitled: 'Nouvelle conversation', conversationMessageCount: '{count} messages', conversationDelete: 'Supprimer la conversation',
    conversationSidebarHint: 'Chaque conversation est stockée localement et continue dans son propre fil App Server en mode Codex.', activeConversationLabel: 'Conversation active', youPrefix: 'Toi :',
    settingsTitle: 'Paramètres', settingsIntro: 'Configure les backends génératifs et les capacités agentiques d’Egomorph Core.', quickActionsTitle: 'Actions rapides', quickActionsHint: 'Gère l’historique, la voix et les données stockées.',
    voiceActivate: 'Activer la voix', voiceDeactivate: 'Désactiver la voix', personalSectionTitle: 'Adresse personnelle', userNameLabel: 'Ton nom', saveUserNameBtn: 'Enregistrer', clearUserNameBtn: 'Supprimer',
    personalSectionHint: 'Egomorph Core peut utiliser ce nom comme préférence locale.', languageSectionTitle: 'Langue', languageLabel: 'Langue',
    infoText: 'Egomorph Core est une application navigateur locale, PWA et agentique avec LLM local et backend API ou Codex optionnel.<br><br>Copyright CreateWithCode 2025 - 2026<br>Licence MIT.',
    resourceProfileTitle: 'Backend génératif', resourceProfileIntro: 'Choisis un backend génératif pour Egomorph Core.',
    resourceProfileFullName: 'Local', resourceProfileFullText: '- LLM génératif dans le navigateur', resourceProfileFullMeta: 'Mémoire selon le modèle, entièrement local', resourceProfileApiText: '- API externe (OpenRouter / OpenAI / Ollama / LM Studio)',
    resourceProfileApiMeta: '~0 Mo localement, nécessite un endpoint API', resourceProfileCodexText: '- Codex App Server local avec connexion ChatGPT', resourceProfileCodexMeta: '~0 Mo dans le navigateur, nécessite le gateway Egomorph Core local', resourceProfileReloadHint: 'Le changement de profil prend effet après rechargement.',
    skillSettingsTitle: 'Compétences', skillSettingsIntro: 'Gère les compétences installées, leurs autorisations, profils et configuration.',
    skillLoading: 'Chargement des manifestes…', skillSystemUnavailable: 'Le système de compétences est indisponible.', skillInstall: 'Installer', skillUninstall: 'Désinstaller', skillEnable: 'Activer la compétence', skillEnabled: 'Activée', skillDisabled: 'Désactivée', skillNotInstalled: 'Non installée',
    skillVersion: 'Version', skillLastRun: 'Dernière exécution', skillNeverRun: 'Jamais', skillPermissions: 'Autorisations requises', skillProfiles: 'Profils autorisés', skillSetup: 'Configuration', skillSave: 'Enregistrer', skillSavedStatus: 'Enregistré', skillUnavailableForProfile: 'La compétence ou ses autorisations requises ne sont pas activées pour le profil courant.',
    skillProfileFull: 'Local', skillProfileApi: 'API', skillProfileCodex: 'Codex', skillPermissionNetwork: 'Accès Internet', skillPermissionNetworkDescription: 'Peut envoyer des recherches à des services externes.', skillPermissionCredentials: 'Utiliser les identifiants locaux', skillPermissionCredentialsDescription: 'Peut utiliser les identifiants Google stockés localement.',
    internetSkillName: 'Recherche Internet', internetSkillDescription: 'Charge des sources Web actuelles comme contexte pour les réponses API et Codex.', internetProviderAuto: 'Automatique : Google puis solutions de repli', internetProviderGoogle: 'Google Programmable Search', internetProviderFallback: 'DuckDuckGo/Wikipédia uniquement', internetSkillEnabledLabel: 'Activer la recherche Internet', internetSkillWarning: 'Les requêtes de recherche sont envoyées au fournisseur sélectionné.', internetSkillProviderLabel: 'Fournisseur de recherche',
    internetSkillGoogleHint: 'Les fournisseurs de repli sont utilisés sans configuration Google. Les clés restent dans le navigateur.', internetSkillSaveBtn: 'Enregistrer', internetSkillTestBtn: 'Tester la recherche', internetSkillSavedStatus: 'Enregistré', internetSkillTestingStatus: 'Test...', internetSkillTestOkStatus: 'Recherche OK ({count} résultats)', internetSkillErrorStatusPrefix: 'Erreur : ', internetSkillTestQuery: 'Recherche Internet Egomorph Core',
    apiSettingsTitle: 'Paramètres API', apiSettingsIntro: 'Connecte Egomorph Core à un LLM externe compatible OpenAI.', apiSettingsWarning: 'Les clés API sont stockées dans le navigateur. Un proxy est plus sûr pour un déploiement public.', apiMaxTokensLabel: 'Tokens de réponse max.', apiMaxTokensHint: 'S’applique uniquement aux réponses API.', apiSaveBtn: 'Enregistrer', apiTestBtn: 'Tester la connexion', apiExamplesTitle: 'Exemples de configuration :', apiSavedStatus: 'Enregistré', apiTestingStatus: 'Test...', apiConnectionOkStatus: 'Connexion OK', apiErrorStatusPrefix: 'Erreur : ',
    codexSettingsTitle: 'Gateway Codex', codexSettingsIntro: 'Utilise le gateway Egomorph Core local vers la CLI Codex officielle avec App Server persistant et streaming.', codexSettingsWarning: 'Réservé à un usage local de confiance. Ne copie pas de cookies, tokens ou auth.json dans l’application.', codexSetupTitle: 'Configuration en 3 étapes',
    codexStepLogin: 'Connecte-toi une fois : <code>./egomorph codex login</code> ou <code>./egomorph codex login --device-auth</code>.', codexStepBridge: 'Lance le gateway : <code>./egomorph dashboard</code> ou <code>./egomorph gateway</code>.', codexStepCheck: 'Enregistre ici puis vérifie avec <strong>Contrôler le statut</strong>.', codexPersistentHint: 'Après connexion, Codex reste connecté localement ; Egomorph Core stocke uniquement l’URL, le modèle et la limite de tokens.', codexBridgeUrlLabel: 'URL du gateway',
    codexMaxTokensLabel: 'Tokens de réponse max.', codexMaxTokensHint: 'S’applique uniquement au mode Codex.', codexSaveBtn: 'Enregistrer', codexTestBtn: 'Tester le gateway', codexStatusBtn: 'Contrôler le statut', codexSavedStatus: 'Enregistré', codexTestingStatus: 'Test...', codexStatusChecking: 'Vérification...', codexConnectionOkStatus: 'Gateway OK', codexErrorStatusPrefix: 'Erreur : ',
    chatModelSettingsTitle: 'Modèle de chat local (LLM)', reloadChatModelBtn: 'Charger le modèle', chatModelStatusIdle: 'Aucun modèle chargé', chatModelLoading: 'Chargement...', chatModelNoTransformers: 'Transformers.js indisponible', chatModelErrorPrefix: 'Erreur : ', chatModelWaitingTransformers: 'Attente de Transformers.js...', chatModelLoadingPct: 'Chargement... {pct}%', chatModelInitializing: 'Initialisation...', chatModelReady: 'Prêt ({id})', chatModelNeedsLoad: 'Charge d’abord un modèle', chatModelApiActive: 'Mode API actif', chatModelCodexActive: 'Mode Codex actif', chatModelProfilePrefix: 'Profil : ', chatModelNoLocalLLM: 'aucun LLM local', llmMaxTokensLabel: 'Tokens max.', llmEnabledLabel: 'Activer les réponses LLM', chatModelSettingsHint: 'Modèle <code>text-generation</code> pour réponses locales autonomes. Aucun repli par règles.', lightChatModelsTitle: 'Modèles légers :'
  }) };
})();
